/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks with optional filters */
        get: operations["listTasks"];
        put?: never;
        /** Create a new task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll for next pending task for a given agent */
        get: operations["pollTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status count summary for all tasks */
        get: operations["getTasksSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by ID */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task status or fields */
        patch: operations["patchTask"];
        trace?: never;
    };
    "/tasks/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a pending task (pending → claimed) */
        post: operations["claimTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/deps-met": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if all dependencies of a task are satisfied */
        get: operations["checkDepsMet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch a single task (create + notify agent session) */
        post: operations["dispatchTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch a chain of tasks with sequential dependencies */
        post: operations["dispatchChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retry-routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all retry routing rules */
        get: operations["listRetryRoutes"];
        put?: never;
        /** Create a retry routing rule */
        post: operations["createRetryRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retry-routing/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a retry routing rule */
        delete: operations["deleteRetryRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chains/{chain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chain status (all tasks + completion flag) */
        get: operations["getChainStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated dashboard data (todo + exceptions + stats) */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task detail with full history timeline */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All task chains grouped by chain_id */
        get: operations["getAPIChains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frontend configuration (known agents, server version) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Task FSM state
         * @enum {string}
         */
        TaskStatus: "pending" | "claimed" | "in_progress" | "review" | "done" | "failed" | "blocked" | "cancelled";
        Task: {
            /** @example 1897f68382d84620 */
            id: string;
            /** @example 实现 OnTaskComplete */
            title: string;
            /** @example 修复单任务 notify_ceo_on_complete 不触发问题 */
            description?: string;
            status: components["schemas"]["TaskStatus"];
            /** @example coder */
            assigned_to?: string;
            /** @example thinker */
            retry_assigned_to?: string;
            /** @description ID of the replacement task (auto-retry creates a new task) */
            superseded_by?: string;
            /** @example chain_1897f68382d83298 */
            chain_id?: string;
            /** @default false */
            notify_ceo_on_complete: boolean;
            /** @default 0 */
            stale_dispatch_count: number;
            parent_id?: string;
            mode?: string;
            /** @default false */
            requires_review: boolean;
            /** @example OnTaskComplete实现完成，2测试通过 */
            result?: string;
            failure_reason?: string;
            /** @example 4 */
            version: number;
            /** @default 0 */
            priority: number;
            /**
             * @description Human task timeout in minutes; null = no timeout
             * @example 60
             */
            timeout_minutes?: number | null;
            /**
             * @description Action on timeout; escalate→blocked, skip→done
             * @enum {string|null}
             */
            timeout_action?: "escalate" | "skip" | null;
            /**
             * Format: uri
             * @example https://github.com/irchelper/agent-queue/commit/e2f142a
             */
            commit_url?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description List of task IDs this task depends on */
            depends_on?: string[];
            history?: components["schemas"]["HistoryItem"][];
        };
        HistoryItem: {
            id: number;
            task_id: string;
            from_status?: string;
            to_status: string;
            changed_by?: string;
            note?: string;
            /** Format: date-time */
            changed_at: string;
        };
        RetryRoute: {
            id: number;
            /** @example coder */
            assigned_to: string;
            /** @example 架构 */
            error_keyword: string;
            /** @example thinker */
            retry_assigned_to: string;
            /** @example 10 */
            priority: number;
        };
        ChainRequest: {
            tasks: components["schemas"]["CreateTaskRequest"][];
            /** @default false */
            notify_ceo_on_complete: boolean;
            chain_title?: string;
        };
        CreateTaskRequest: {
            title: string;
            description?: string;
            assigned_to?: string;
            retry_assigned_to?: string;
            chain_id?: string;
            /** @default false */
            notify_ceo_on_complete: boolean;
            parent_id?: string;
            mode?: string;
            /** @default false */
            requires_review: boolean;
            /** @default 0 */
            priority: number;
            timeout_minutes?: number | null;
            /** @enum {string|null} */
            timeout_action?: "escalate" | "skip" | null;
            /** Format: uri */
            commit_url?: string | null;
            depends_on?: string[];
        };
        PatchTaskRequest: {
            status?: components["schemas"]["TaskStatus"];
            result?: string;
            failure_reason?: string;
            retry_assigned_to?: string;
            /** Format: uri */
            commit_url?: string | null;
            note?: string;
            changed_by?: string;
            version: number;
        };
        DispatchRequest: {
            title: string;
            description?: string;
            assigned_to: string;
            /** @default false */
            notify_ceo_on_complete: boolean;
            /** @default 0 */
            priority: number;
            /** @default false */
            requires_review: boolean;
            timeout_minutes?: number | null;
            timeout_action?: string | null;
            /** Format: uri */
            commit_url?: string | null;
            depends_on?: string[];
        };
        ErrorResponse: {
            /** @example task not found */
            error: string;
        };
        DashboardStats: {
            total?: number;
            pending?: number;
            in_progress?: number;
            done?: number;
            failed?: number;
            blocked?: number;
        };
        AgentInfo: {
            name?: string;
            label?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Business rule violation (e.g. invalid FSM transition) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Version conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example ok */
                        database?: string;
                    };
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                assigned_to?: string;
                parent_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tasks?: components["schemas"]["Task"][];
                        total?: number;
                    };
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    pollTask: {
        parameters: {
            query: {
                assigned_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next pending task (null if none available) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        task?: (components["schemas"]["Task"] | null) | null;
                    };
                };
            };
        };
    };
    getTasksSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary counts by status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTaskRequest"];
            };
        };
        responses: {
            /** @description Updated task with triggered downstream IDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        task?: components["schemas"]["Task"];
                        triggered?: string[];
                        blocked_downstream?: {
                            id?: string;
                            title?: string;
                            assigned_to?: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    claimTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    agent?: string;
                    version: number;
                };
            };
        };
        responses: {
            /** @description Claimed task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    checkDepsMet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deps status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deps_met?: boolean;
                        task_id?: string;
                    };
                };
            };
        };
    };
    dispatchTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Dispatched task */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    dispatchChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChainRequest"];
            };
        };
        responses: {
            /** @description Created chain */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chain_id?: string;
                        tasks?: components["schemas"]["Task"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listRetryRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All routing rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        count?: number;
                        routes?: components["schemas"]["RetryRoute"][];
                    };
                };
            };
        };
    };
    createRetryRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    assigned_to: string;
                    /** @default  */
                    error_keyword?: string;
                    retry_assigned_to: string;
                    /** @default 0 */
                    priority?: number;
                };
            };
        };
        responses: {
            /** @description Created routing rule */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryRoute"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteRetryRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getChainStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chain_id?: string;
                        complete?: boolean;
                        tasks?: components["schemas"]["Task"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Pending tasks (all assigned_to values) */
                        todo?: components["schemas"]["Task"][];
                        /** @description Failed and blocked tasks */
                        exceptions?: components["schemas"]["Task"][];
                        stats?: components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task + history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        task?: components["schemas"]["Task"];
                        history?: components["schemas"]["HistoryItem"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAPIChains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chains?: {
                            chain_id?: string;
                            tasks?: components["schemas"]["Task"][];
                        }[];
                    };
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents?: components["schemas"]["AgentInfo"][];
                        /** @example v12 */
                        version?: string;
                    };
                };
            };
        };
    };
}
